name = "ChemicalKinetics"
uuid = "929da9e8-5203-495f-90b2-577e54eea2cc"
authors = ["Leo Basov <leo.basov@dlr.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
